<html>
<body>
<h2>Descrição do problema</h2>
<p>Após configurar o AWS / S3, antes de fazer o <b><i>push</i></b>, tentei resolver um erro recorrente: arquivos que, embora estivessem no <b>.gitignore</b>, foram rastreados pelo <b>Git</b></p>
<p>Para tratar a questão usei a solução descrita em: <a href="x">x</a></p>
<p>A solução faz com que os arquivos, especial o <b>.env</b>, doravante, não sejam rastreados, mas não <i>limpa</i> o passado.</p>

<h3>Acesse:</h3>
<p>Repositório: <a href="https://github.com/fernandolcouto/repo_py392">https://github.com/fernandolcouto/repo_py392</a></p>
<p>O problema: <b><i>exposição de informação sensível: </i></b><a href="https://github.com/fernandolcouto/repo_py392/blob/b09bffda1d4f3d80206e885152792c83ea9e8d9d/.env">https://github.com/fernandolcouto/repo_py392/blob/b09bffda1d4f3d80206e885152792c83ea9e8d9d/.env</a></p>




<p>Para tratar o passado, tentei <a href="https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository">Removing sensitive data from a repository</a>. Contudo, recebo o erro descrito abaixo.</p>
<p>O que eu estou perdendo? Agradeço por qualquer ajuda. Obrigado!</p>

<h3>Criado um Branch para tratar a questão</h3>
<pre><font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (work_django1)$ git checkout -b fix_with_filter_branch
Switched to a new branch &apos;fix_with_filter_branch&apos;
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (fix_with_filter_branch)$ git status
On branch fix_with_filter_branch
nothing to commit, working tree clean
<h3>Pasta do Repositório:</h3>
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (fix_with_filter_branch)$ ls -la
total 96
drwxr-xr-x 9 flc2 flc2 4096 mar 30 17:47 <font color="#5555FF"><b>.</b></font>
drwxr-xr-x 4 flc2 flc2 4096 mar 27 11:46 <font color="#5555FF"><b>..</b></font>
drwxr-xr-x 5 flc2 flc2 4096 mar 27 11:46 <font color="#5555FF"><b>base</b></font>
drwxr-xr-x 2 flc2 flc2 4096 mar 27 11:46 <font color="#5555FF"><b>contrib</b></font>
-rw-r--r-- 1 flc2 flc2    0 mar 30 17:40 db.sqlite3
-rw-r--r-- 1 flc2 flc2  322 mar 30 17:47 .env
-rw-r--r-- 1 flc2 flc2   44 mar 27 11:46 .flake8
drwxr-xr-x 8 flc2 flc2 4096 mar 30 18:44 <font color="#5555FF"><b>.git</b></font>
drwxr-xr-x 3 flc2 flc2 4096 mar 27 11:46 <font color="#5555FF"><b>.github</b></font>
-rw-r--r-- 1 flc2 flc2 2139 mar 30 17:40 .gitignore
-rw-r--r-- 1 flc2 flc2 1073 mar 27 11:46 LICENSE
-rwxr-xr-x 1 flc2 flc2  666 mar 27 11:46 <font color="#55FF55"><b>manage.py</b></font>
-rw-r--r-- 1 flc2 flc2  306 mar 27 11:46 old_requirements-dev.txt
-rw-r--r-- 1 flc2 flc2   88 mar 27 11:46 old_requirements.txt
-rw-r--r-- 1 flc2 flc2   43 mar 27 11:46 Procfile
-rw-r--r-- 1 flc2 flc2  114 mar 27 11:46 pytest.ini
-rw-r--r-- 1 flc2 flc2  519 mar 28 14:06 README.md
drwxr-xr-x 3 flc2 flc2 4096 mar 29 13:53 <font color="#5555FF"><b>repo_py392</b></font>
-rw-r--r-- 1 flc2 flc2  125 mar 27 11:46 requirements.in
-rw-r--r-- 1 flc2 flc2 9347 mar 27 11:46 requirements.txt
-rw-r--r-- 1 flc2 flc2   13 mar 27 11:46 runtime.txt
drwxr-xr-x 2 flc2 flc2 4096 mar 30 18:20 <font color="#5555FF"><b>terminotes_repo_py392</b></font>
drwxr-xr-x 2 flc2 flc2 4096 mar 30 17:40 <font color="#5555FF"><b>.vscode</b></font>
<h3>git filter-branch:</h3>
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (fix_with_filter_branch)$ git filter-branch --force --index-filter \
  &quot;git rm --cached --ignore-unmatch /home/flcs/pyproj/repo_py392/repo_py392/.env&quot; \
  --prune-empty --tag-name-filter cat -- --all
WARNING: git-filter-branch has a glut of gotchas generating mangled history
	 rewrites.  Hit Ctrl-C before proceeding to abort, then use an
	 alternative filtering tool such as &apos;git filter-repo&apos;
	 (https://github.com/newren/git-filter-repo/) instead.  See the
	 filter-branch manual page for more details; to squelch this warning,
	 set FILTER_BRANCH_SQUELCH_WARNING=1.
Proceeding with filter-branch...

Rewrite 087686bae980b0a901c380ab1d956c883e68d3e3 (1/54) (0 seconds passed, remaining 0 predicted)    <span style='background-color:yellow'>fatal: Invalid path &apos;/home/flcs/pyproj/repo_py392&apos;: Arquivo ou diretório inexistente
index filter failed: git rm --cached --ignore-unmatch /home/flcs/pyproj/repo_py392/repo_py392/.env</pre></span>

<h3>Uma solução</h3>
<p><a href="https://stackoverflow.com/questions/43762338/how-to-remove-file-from-git-history">How to remove file from Git history?</a></p>
<pre><font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (fix_with_filter_branch)$ git filter-branch --tree-filter &apos;rm -f /home/flcs/pyproj/repo_py392/repo_py392/.env&apos; HEAD
WARNING: git-filter-branch has a glut of gotchas generating mangled history
	 rewrites.  Hit Ctrl-C before proceeding to abort, then use an
	 alternative filtering tool such as &apos;git filter-repo&apos;
	 (https://github.com/newren/git-filter-repo/) instead.  See the
	 filter-branch manual page for more details; to squelch this warning,
	 set FILTER_BRANCH_SQUELCH_WARNING=1.
Proceeding with filter-branch...

Rewrite 138a082d7741947819fc9cd575f294a548052a0e (48/53) (9 seconds passed, remaining 0 predicted)     
Ref &apos;refs/heads/fix_with_filter_branch&apos; was rewritten</pre>

<h3>Mudando para o branch work_django1</h3>

<pre><font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (fix_with_filter_branch)$ ls -la
total 96
drwxr-xr-x 9 flc2 flc2 4096 mar 30 20:06 <font color="#5555FF"><b>.</b></font>
drwxr-xr-x 4 flc2 flc2 4096 mar 27 11:46 <font color="#5555FF"><b>..</b></font>
drwxr-xr-x 5 flc2 flc2 4096 mar 27 11:46 <font color="#5555FF"><b>base</b></font>
drwxr-xr-x 2 flc2 flc2 4096 mar 27 11:46 <font color="#5555FF"><b>contrib</b></font>
-rw-r--r-- 1 flc2 flc2    0 mar 30 17:40 db.sqlite3
-rw-r--r-- 1 flc2 flc2  322 mar 30 17:47 .env
-rw-r--r-- 1 flc2 flc2   44 mar 27 11:46 .flake8
drwxr-xr-x 8 flc2 flc2 4096 mar 30 20:06 <font color="#5555FF"><b>.git</b></font>
drwxr-xr-x 3 flc2 flc2 4096 mar 27 11:46 <font color="#5555FF"><b>.github</b></font>
-rw-r--r-- 1 flc2 flc2 2139 mar 30 17:40 .gitignore
-rw-r--r-- 1 flc2 flc2 1073 mar 27 11:46 LICENSE
-rwxr-xr-x 1 flc2 flc2  666 mar 27 11:46 <font color="#55FF55"><b>manage.py</b></font>
-rw-r--r-- 1 flc2 flc2  306 mar 27 11:46 old_requirements-dev.txt
-rw-r--r-- 1 flc2 flc2   88 mar 27 11:46 old_requirements.txt
-rw-r--r-- 1 flc2 flc2   43 mar 27 11:46 Procfile
-rw-r--r-- 1 flc2 flc2  114 mar 27 11:46 pytest.ini
-rw-r--r-- 1 flc2 flc2  519 mar 28 14:06 README.md
drwxr-xr-x 3 flc2 flc2 4096 mar 29 13:53 <font color="#5555FF"><b>repo_py392</b></font>
-rw-r--r-- 1 flc2 flc2  125 mar 27 11:46 requirements.in
-rw-r--r-- 1 flc2 flc2 9347 mar 27 11:46 requirements.txt
-rw-r--r-- 1 flc2 flc2   13 mar 27 11:46 runtime.txt
drwxr-xr-x 2 flc2 flc2 4096 mar 30 20:12 <font color="#5555FF"><b>terminotes_repo_py392</b></font>
drwxr-xr-x 2 flc2 flc2 4096 mar 30 17:40 <font color="#5555FF"><b>.vscode</b></font>
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (fix_with_filter_branch)$ cat .env
DEBUG=True
SECRET_KEY=definida CHAVE SECRETA
ALLOWED_HOSTS=localhost, 127.0.0.1
AWS_ACCESS_KEY_ID = AKIA4PAVQ4BAB7Y26WVU
AWS_SECRET_ACCESS_KEY = 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
# 7XxaBrY7JUNGcNiTYRuVU+/JLxkTnpJrtNBB5RE8
AWS_STORAGE_BUCKET_NAME = aularepo392py
# Comentario: Testando correção arquivos ignorados
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (fix_with_filter_branch)$ git checkout work_django1
Switched to branch &apos;work_django1&apos;
Your branch is up to date with &apos;origin/work_django1&apos;.
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (work_django1)$ git status
On branch work_django1
Your branch is up to date with &apos;origin/work_django1&apos;.

nothing to commit, working tree clean
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (work_django1)$ git status
On branch work_django1
Your branch is up to date with &apos;origin/work_django1&apos;.

nothing to commit, working tree clean
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (work_django1)$ git filter-branch --tree-filter &apos;rm -f /home/flcs/pyproj/repo_py392/repo_py392/.env&apos; HEAD
WARNING: git-filter-branch has a glut of gotchas generating mangled history
	 rewrites.  Hit Ctrl-C before proceeding to abort, then use an
	 alternative filtering tool such as &apos;git filter-repo&apos;
	 (https://github.com/newren/git-filter-repo/) instead.  See the
	 filter-branch manual page for more details; to squelch this warning,
	 set FILTER_BRANCH_SQUELCH_WARNING=1.
Proceeding with filter-branch...

Cannot create a new backup.
A previous backup already exists in refs/original/
Force overwriting the backup with -f
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (work_django1)$ git branch
  copy_dev01_main
  fix_with_filter_branch
  main
* <font color="#00AA00">work_django1</font>
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (work_django1)$ git status
On branch work_django1
Your branch is up to date with &apos;origin/work_django1&apos;.

nothing to commit, working tree clean
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (work_django1)$ git rebase fix_with_filter_branch
Successfully rebased and updated refs/heads/work_django1.
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (work_django1)$ git remote -v
heroku	https://git.heroku.com/repo392py.git (fetch)
heroku	https://git.heroku.com/repo392py.git (push)
origin	git@github.com:fernandolcouto/repo_py392.git (fetch)
origin	git@github.com:fernandolcouto/repo_py392.git (push)
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (work_django1)$ git push origin
Enter passphrase for key &apos;/home/flc2/.ssh/id_ed25519&apos;: 
Enumerating objects: 12313, done.
Counting objects: 100% (12313/12313), done.
Delta compression using up to 8 threads
Compressing objects: 100% (6611/6611), done.
Writing objects: 100% (12313/12313), 14.51 MiB | 621.00 KiB/s, done.
Total 12313 (delta 4555), reused 12215 (delta 4526), pack-reused 0
remote: Resolving deltas: 100% (4555/4555), done.
remote: 
remote: Create a pull request for &apos;work_django1&apos; on GitHub by visiting:
remote:      https://github.com/fernandolcouto/repo_py392/pull/new/work_django1
remote: 
To github.com:fernandolcouto/repo_py392.git
 * [new branch]      work_django1 -&gt; work_django1
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (work_django1)$ git branch
  copy_dev01_main
  fix_with_filter_branch
  main
* <font color="#00AA00">work_django1</font>
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (work_django1)$ git checkout main
Switched to branch &apos;main&apos;
Your branch is up to date with &apos;origin/main&apos;.
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (main)$ git status
On branch main
Your branch is up to date with &apos;origin/main&apos;.

nothing to commit, working tree clean
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (main)$ git checkout -b copy_dev02_main
Switched to a new branch &apos;copy_dev02_main&apos;
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (copy_dev02_main)$ git status
On branch copy_dev02_main
nothing to commit, working tree clean
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (copy_dev02_main)$ git filter-branch --tree-filter &apos;rm -f /home/flcs/pyproj/repo_py392/repo_py392/.env&apos; HEAD
WARNING: git-filter-branch has a glut of gotchas generating mangled history
	 rewrites.  Hit Ctrl-C before proceeding to abort, then use an
	 alternative filtering tool such as &apos;git filter-repo&apos;
	 (https://github.com/newren/git-filter-repo/) instead.  See the
	 filter-branch manual page for more details; to squelch this warning,
	 set FILTER_BRANCH_SQUELCH_WARNING=1.
Proceeding with filter-branch...

Cannot create a new backup.
A previous backup already exists in refs/original/
Force overwriting the backup with -f
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (copy_dev02_main)$ git -f filter-branch --tree-filter &apos;rm -f /home/flcs/pyproj/repo_py392/repo_py392/.env&apos; HEAD
unknown option: -f
usage: git [--version] [--help] [-C &lt;path&gt;] [-c &lt;name&gt;=&lt;value&gt;]
           [--exec-path[=&lt;path&gt;]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=&lt;path&gt;] [--work-tree=&lt;path&gt;] [--namespace=&lt;name&gt;]
           &lt;command&gt; [&lt;args&gt;]
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (copy_dev02_main)$ git filter-branch --tree-filter -f &apos;rm -f /home/flcs/pyproj/repo_py392/repo_py392/.env&apos; HEAD
WARNING: git-filter-branch has a glut of gotchas generating mangled history
	 rewrites.  Hit Ctrl-C before proceeding to abort, then use an
	 alternative filtering tool such as &apos;git filter-repo&apos;
	 (https://github.com/newren/git-filter-repo/) instead.  See the
	 filter-branch manual page for more details; to squelch this warning,
	 set FILTER_BRANCH_SQUELCH_WARNING=1.
Proceeding with filter-branch...

Cannot create a new backup.
A previous backup already exists in refs/original/
Force overwriting the backup with -f
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (copy_dev02_main)$ git checkout work_django1
Switched to branch &apos;work_django1&apos;
Your branch is up to date with &apos;origin/work_django1&apos;.
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (work_django1)$ git push --help
<font color="#55FF55"><b>flc2@db</b></font>:<font color="#5555FF"><b>~/pyproj/repo_py392/repo_py392</b></font> (work_django1)$ git branch
  copy_dev01_main
  copy_dev02_main
  fix_with_filter_branch
  main
* <font color="#00AA00">work_django1</font></pre>

<h4>Um clone do repositório remoto está em <b>fix_security</b></h4>


</body>
</html>